### ISSUE TITLE
Fix Mapper activity inputs

### ISSUE THREAD

**Issue by dcsouthwick** [project-flogo/contrib#108]
Currently, mapper shows no inputs, making it non-functional in the UI

![mapper](https://user-images.githubusercontent.com/3515570/73363163-77cbb800-42a8-11ea-9187-3ce345954255.png)

**Comment by skothari-tibco** [comment]
Do you have inputs in the input/output section of the flow; just right of trigger.

**Comment by dcsouthwick** [comment]
I have a MQTT trigger mapped to message[object]

**Comment by skothari-tibco** [comment]
You'll need to add output in the input/output section of the flow; It should be just right of trigger; the long bar .
