### ISSUE TITLE
rest invoke output name mismatch in descriptor.json and runtime metadata

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/contrib#41]
Descriptor json defines as `result`:
```
  "output": [
    {
      "name": "status",
      "type": "int",
      "description" : "The HTTP status code"
    },
    {
      "name": "result",
      "type": "any",
      "description" : "The HTTP response data"
    }
  ]
```

But runtime metadata define as `data`
```
type Output struct {
	Status int         `md:"status"` // The HTTP status code
	Data   interface{} `md:"data"`   // The HTTP response data
}
```

**Comment by skothari-tibco** [comment]
I think https://github.com/project-flogo/core/blob/master/activity/metadata.go#L18 will help you understand.

**Comment by vijaynalawade** [comment]
@skothari-tibco : @lixingwang pointing out that output metadata attributes are not in sync with descriptor.json.

**Comment by lixingwang** [comment]
@skothari-tibco I meant the output filed name not in sync. descriptor.json defined as `result` but runtime metadata define as `data`

**Comment by skothari-tibco** [comment]
Ohh. Yeah that's not correct. Thanks for pointing that out.

**Comment by fm-tibco** [comment]
Any opinions on whether it should be data or result?  @mellistibco thoughts?

**Comment by skothari-tibco** [comment]
I think it should be data. As it is meant to be content of the result and not the result itself.

**Comment by vijaynalawade** [comment]
I would go with `data`.
