### ISSUE TITLE
Install contrib not working

### ISSUE THREAD

**Issue by jkoenig72** [project-flogo/contrib#57]
Try to execute 
fritz@ubuntu:~$ flogo install github.com/project-flogo/contrib/activity/log
Error validating project: not a valid flogo app project directory, missing 'src' diretory

Seems to be same for all addons.

**Comment by skothari-tibco** [comment]
You should be running this command in the Flogo App `dir` . 
Eg. 
`flogo create myAPP`
`cd myApp/`
`flogo install github.com/project-flogo/contrib/activity/log` .
