### ISSUE TITLE
channel activity has inconsistent between metadata and description

### ISSUE THREAD

**Issue by masterclock** [project-flogo/contrib#63]
https://github.com/project-flogo/contrib/blob/9d5e9830c1a1af6dc5972bde158f6db0c6500c0a/activity/channel/descriptor.json#L16
name is "value", but
https://github.com/project-flogo/contrib/blob/9d5e9830c1a1af6dc5972bde158f6db0c6500c0a/activity/channel/metadata.go#L9
name is "data"

**Comment by skothari-tibco** [comment]
Thanks for bringing that to our attention.
