### ISSUE TITLE
REST Invoke - Path and Query Params not working

### ISSUE THREAD

**Issue by akpuvvada** [project-flogo/contrib#88]
Below is the Rest Invoke Activity definition. I changed the key for security.

I am getting below error when I try to run it.

```
2019-11-27T16:14:26.909-0500    INFO    [flogo.activity.log] -  404 -> {"Code":"404","Message":"Not found","Reference":"/currentconditions/v1?apikey=95df38db964c4236936b1e894ad2232f","Exception":null}
```

The same mapping is working fine when I use in logger and getting json logged.

Mapping: `"=string.concat('{\"zipC\": \"', $flow.CityCode_Input, '\"}')"`

Log Entry: `
2019-11-27T16:14:26.722-0500    INFO    [flogo.activity.log] -  '{"zipC": "70604"}' - HostID [3758ec316bc59a057d4364336a20b3bc], HostName [Lambda_GET_WeatherLimit_POC], Activity [Log_Request]`

```
{
            "id": "rest_3",
            "name": "AccuWeather_GET_RESTInvoke",
            "description": "Invokes a REST Service",
            "activity": {
              "ref": "#rest",
              "input": {
                "pathParams": "=string.concat('{\"zipC\": \"', $flow.CityCode_Input, '\"}')",
                "queryParams": "=string.concat('{\"apikey\": \"', 'N1KaG63pxFWtIQRcZuKX9', '\"}')"
              },
              "settings": {
                "uri": "http://dataservice.accuweather.com/currentconditions/v1/:zipC?",
                "method": "GET"
              }
            }
          }
```

**Comment by fm-tibco** [comment]
Can you remove the ‘?’ from the end of the URI.

**Comment by akpuvvada** [comment]
Thanks Frank. That worked.
